name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive
      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build with Gradle
        run: ./gradlew build -x test allTests
        env:
          TZ: 'Asia/Tokyo'
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          EEWBOT_RENDERER_ADDRESS: ${{ secrets.EEWBOT_RENDERER_ADDRESS }}
          EEWBOT_RENDERER_KEY: ${{ secrets.EEWBOT_RENDERER_KEY }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/test-results/
